# Application bindings
bindd = SUPER RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" yazi
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu


# bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
# bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
# bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
# bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
# bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
# bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
# bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
# bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
unbind = SUPER, RETURN
unbind = SUPER SHIFT, D
unbind = SUPER ALT SHIFT, F
unbind = SUPER SHIFT, O
unbind = SUPER SHIFT, B
unbind = SUPER SHIFT, RETURN
unbind = SUPER SHIFT ALT, B
unbind = SUPER SHIFT, M